### ISSUE TITLE
one-to-one mapping

### ISSUE THREAD

**Issue by chenhuiphd** [VSAnimator/stgan#2]
hi,I want to choose one-to-one mapping mode for network training, how should I choose the model option in the base_options.py file, or what parts of the code should be modified. Thank you

 parser.add_argument('--model', type=str, default='base_model', help='chooses which model to use. [cycle_gan | pix2pix | test | colorization]')

**Comment by VSAnimator** [comment]
This repo builds on https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix, which illustrates the syntax for one-to-one mapping. The --input_nc command line option will need to be set to 4 if using IR data in addition to RGB.

Here is an example command line input for 3-channel one-to-one mapping, taken from the link above:
python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix

The parser help string is out of date as it does not reflect the "stgan" model option, I will update this.
