### ISSUE TITLE
Reproduce result

### ISSUE THREAD

**Issue by come880412** [VSAnimator/stgan#5]
Hello,
I followed your step to train the stgan model. 
But I got a bad result. I would like to ask if the way you calculate PSNR is to add up all of them and take the average?

Here is the command of training I used:
python train.py --dataroot ./spilt_data/multiImages/combined_ir  --name stgan_unet --model temporal_branched_ir --netG unet_256_independent --dataset_mode temporal_ir --input_nc 4  --batch_size 128

Thank you.

**Comment by VSAnimator** [comment]
Hi,

When you say you got a bad result, what specifically do you see? Are the images produced qualitatively similar to those in the paper? How many epochs did you train for, and on what epoch did you evaluate the model? In addition, did you calculate SSIM, and if so what SSIM numbers did you get?

Thanks

**Comment by come880412** [comment]
I'm sorry about that.

There is a big problem in my PSNR calculation program. After I modified it, it worked correctly.

Thanks
